- name: Add remote nodes for Assisted Installer
  hosts: localhost
  collections:
   - community.general
  gather_facts: no
  vars:
    - baremetalhosts: "{{ lookup('file', lookup('env', 'REMOTE_BAREMETALHOSTS_FILE')) | from_json }}"
    - infraenv_name: "{{ lookup('env', 'ASSISTED_INFRAENV_NAME') }}"
    - spoke_namespace: "{{ lookup('env', 'SPOKE_NAMESPACE') }}"
    - cluster_deployment_name: "{{ lookup('env', 'ASSISTED_CLUSTER_DEPLOYMENT_NAME') }}"
    - pull_secret_name: "{{ lookup('env', 'ASSISTED_PULLSECRET_NAME') }}"
    - ssh_public_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - day2: "true"
    - day2_masters: "{{ lookup('env', 'DAY2_MASTERS') }}"
    - baremetalhosts_ignition_override: "{{ lookup('env', 'BAREMETALHOSTS_IGNITION_OVERRIDE', default='') }}"

  tasks:
  - name: optional-latebinding
    block:
    - name: write the infraEnv crd
      template:
        src: "infraEnv-latebinding.j2"
        dest: "generated/day2-latebinding-infraenv.yaml"
    - name: apply infraenvs with oc
      ansible.builtin.command: "oc apply -f generated/day2-latebinding-infraenv.yaml"
    when: cluster_deployment_name == ""
  - name: generate-crds-and-apply
    block:
    - name: create directory for generated CRDs
      file:
        name: generated
        state: directory
    - name: write the remote baremetalHost crds
      template:
        src: "baremetalHost.j2"
        dest: "generated/remote_host_manifests.yaml"
    - name: apply baremetalhosts with oc
      ansible.builtin.command: "oc apply -f generated/remote_host_manifests.yaml"
