- name: Create BareMetalHost CR
  hosts: localhost
  collections:
   - community.general
  gather_facts: no
  vars:
    - spoke_namespace: "{{ lookup('env', 'SPOKE_NAMESPACE') }}"
    - spoke_controlplane_agents: "{{ lookup('env', 'SPOKE_CONTROLPLANE_AGENTS') }}"
    - spoke_api_vip: "{{ lookup('env', 'SPOKE_API_VIP') }}"
    - spoke_ingress_vip: "{{ lookup('env', 'SPOKE_INGRESS_VIP') }}"
    - cluster_name: "{{ lookup('env', 'ASSISTED_CLUSTER_NAME') }}"
    - cluster_image_set_name: "{{ lookup('env', 'ASSISTED_OPENSHIFT_VERSION') }}"
    - cluster_release_image: "{{ lookup('env', 'ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE') }}"
    - cluster_deployment_name: "{{ lookup('env', 'ASSISTED_CLUSTER_DEPLOYMENT_NAME') }}"
    - agent_cluster_install_name: "{{ lookup('env', 'ASSISTED_AGENT_CLUSTER_INSTALL_NAME') }}"
    - pull_secret_name: "{{ lookup('env', 'ASSISTED_PULLSECRET_NAME') }}"
    - ssh_private_key_name: "{{ lookup('env', 'ASSISTED_PRIVATEKEY_NAME') }}"
    - ssh_public_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - baremetalhosts: "{{ lookup('file', lookup('env', 'EXTRA_BAREMETALHOSTS_FILE')) | from_json }}"
    - iso_download_url: "{{ lookup('env', 'ISO_DOWNLOAD_URL') }}"
    - spoke_namespace: "{{ lookup('env', 'SPOKE_NAMESPACE') }}"
    - infraenv_name: "{{ lookup('env', 'ASSISTED_INFRAENV_NAME') }}"

  tasks:
  - name: create directory for generated resources
    file:
      name: generated
      state: directory

  - name: write the baremetalHost CR
    template:
      src: "templates/baremetalHost.j2"
      dest: "generated/baremetalHost.yaml"

