apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: assisted-installer-monitor
  name: assisted-installer
  namespace: REPLACE_NAMESPACE
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: assisted-service
    path: /metrics
    params:
      'match[]':
        - '{__name__=~".+"}'
    scheme: http
  namespaceSelector:
    matchNames:
    - REPLACE_NAMESPACE
  selector:
    matchLabels:
      app: "assisted-service"
