apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: assisted-service
  name: assisted-service
  namespace: REPLACE_NAMESPACE
spec:
  ports:
    - name: assisted-service
      port: 8090
      protocol: TCP
      targetPort: 8090
      nodePort: 30000
  selector:
    app: assisted-service
  type: LoadBalancer
status:
  loadBalancer: {}
