kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: assisted-installer
  namespace: REPLACE_NAMESPACE
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  rules:
    - host: REPLACE_HOSTNAME
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: assisted-service
                port:
                  number: 8090
          - path: "/ready"
            pathType: Prefix
            backend:
              service:
                name: assisted-service
                port:
                  number: 8090
          - path: "/images"
            pathType: Prefix
            backend:
              service:
                name: assisted-image-service
                port:
                  number: 8080
          - path: "/boot-artifacts"
            pathType: Prefix
            backend:
              service:
                name: assisted-image-service
                port:
                  number: 8080
          - path: "/byid"
            pathType: Prefix
            backend:
              service:
                name: assisted-image-service
                port:
                  number: 8080
          - path: "/bytoken"
            pathType: Prefix
            backend:
              service:
                name: assisted-image-service
                port:
                  number: 8080
          - path: "/byapikey"
            pathType: Prefix
            backend:
              service:
                name: assisted-image-service
                port:
                  number: 8080
          - path: "/health"
            pathType: Prefix
            backend:
              service:
                name: assisted-image-service
                port:
                  number: 8080
