apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bm-inventory
spec:
  selector:
    matchLabels:
      app: bm-inventory
  replicas: 1
  template:
    metadata:
      labels:
        app: bm-inventory
    spec:
      containers:
        - name: bm-inventory
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: s3-config
            - configMapRef:
                name: bm-inventory-config
          env:
            - name: IMAGE_BUILDER_CMD
              value: ""
