apiVersion: v1
kind: ConfigMap
metadata:
  name: bm-inventory-config
  namespace: assisted-installer
  labels:
    app: bm-inventory
data:
  INVENTORY_URL: REPLACE_URL
  INVENTORY_PORT: REPLACE_PORT
  NAMESPACE: assisted-installer
  BASE_DNS_DOMAINS: name1:id1/provider1,name2:id2/provider2