kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: assisted-installer-ui
  namespace: REPLACE_NAMESPACE
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  rules:
    - host: REPLACE_HOSTNAME
      http:
        paths:
          - backend:
              serviceName: ocp-metal-ui
              servicePort: 80
