apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  mustGatherImages:
  - name: cnv
    openshiftVersion: '4.8'
    url: registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5
  - name: ocs
    openshiftVersion: '4.8'
    url: registry.redhat.io/ocs4/ocs-must-gather-rhel8
  - name: lso
    openshiftVersion: '4.8'
    url: registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: '4.9'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.9/4.9.45/rhcos-4.9.45-x86_64-live.x86_64.iso
    version: 49.84.202207192205-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.10'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-x86_64-live.x86_64.iso
    version: 410.84.202210040010-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.10'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-aarch64-live.aarch64.iso
    version: 410.84.202210040011-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.11/4.11.48/rhcos-4.11.48-x86_64-live.x86_64.iso
    version: 411.86.202308081056-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.11/4.11.48/rhcos-4.11.48-aarch64-live.aarch64.iso
    version: 411.86.202308081056-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.11/4.11.48/rhcos-4.11.48-s390x-live.s390x.iso
    version: 411.86.202308081056-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.11/4.11.48/rhcos-4.11.48-ppc64le-live.ppc64le.iso
    version: 411.86.202308081056-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.12/4.12.30/rhcos-4.12.30-x86_64-live.x86_64.iso
    version: 412.86.202308081039-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.12/4.12.30/rhcos-4.12.30-aarch64-live.aarch64.iso
    version: 412.86.202308081039-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.12/4.12.30/rhcos-4.12.30-s390x-live.s390x.iso
    version: 412.86.202308081039-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.12/4.12.30/rhcos-4.12.30-ppc64le-live.ppc64le.iso
    version: 412.86.202308081039-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.13/4.13.10/rhcos-4.13.10-x86_64-live.x86_64.iso
    version: 413.92.202307260246-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.13/4.13.10/rhcos-4.13.10-aarch64-live.aarch64.iso
    version: 413.92.202307260246-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.13/4.13.10/rhcos-4.13.10-ppc64le-live.ppc64le.iso
    version: 413.92.202307260246-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.13/4.13.10/rhcos-4.13.10-s390x-live.s390x.iso
    version: 413.92.202307260246-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.14'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.14/4.14.34/rhcos-4.14.34-x86_64-live.x86_64.iso
    version: 414.92.202407091253-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.14'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.14/4.14.34/rhcos-4.14.34-aarch64-live.aarch64.iso
    version: 414.92.202407091253-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.14'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.14/4.14.34/rhcos-4.14.34-ppc64le-live.ppc64le.iso
    version: 414.92.202407091253-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.14'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.14/4.14.34/rhcos-4.14.34-s390x-live.s390x.iso
    version: 414.92.202407091253-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.16'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.16/4.16.51/rhcos-4.16.51-x86_64-live.x86_64.iso
    version: 416.94.202510081640-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.16'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.16/4.16.36/rhcos-4.16.36-aarch64-live.aarch64.iso
    version: 416.94.202501270445-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.16'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.16/4.16.51/rhcos-4.16.51-ppc64le-live.ppc64le.iso
    version: 416.94.202510081640-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.16'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.16/4.16.51/rhcos-4.16.51-s390x-live.s390x.iso
    version: 416.94.202510081640-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.17'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.17/4.17.42/rhcos-4.17.42-x86_64-live.x86_64.iso
    version: 417.94.202507291008-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.17'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.17/4.17.38/rhcos-4.17.38-aarch64-live.aarch64.iso
    version: 417.94.202507291008-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.17'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.17/4.17.41/rhcos-4.17.41-ppc64le-live.ppc64le.iso
    version: 417.94.202507291008-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.17'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.17/4.17.41/rhcos-4.17.41-s390x-live.s390x.iso
    version: 417.94.202507291008-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.18'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.18/4.18.27/rhcos-4.18.27-x86_64-live.x86_64.iso
    version: 418.94.202510081222-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.18'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.18/4.18.27/rhcos-4.18.27-aarch64-live.aarch64.iso
    version: 418.94.202510081222-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.18'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.18/4.18.27/rhcos-4.18.27-ppc64le-live.ppc64le.iso
    version: 418.94.202510081222-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.18'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.18/4.18.27/rhcos-4.18.27-s390x-live.s390x.iso
    version: 418.94.202510081222-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.10/rhcos-4.19.10-x86_64-live-iso.x86_64.iso
    version: 9.6.20250826-1
  - cpuArchitecture: arm64
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.19/4.19.10/rhcos-4.19.10-aarch64-live-iso.aarch64.iso
    version: 9.6.20250826-1
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.19/4.19.10/rhcos-4.19.10-ppc64le-live-iso.ppc64le.iso
    version: 9.6.20250826-1
  - cpuArchitecture: s390x
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.19/4.19.10/rhcos-4.19.10-s390x-live-iso.s390x.iso
    version: 9.6.20250826-1
  - cpuArchitecture: x86_64
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-x86_64-live-iso.x86_64.iso
    version: 9.6.20250826-1
  - cpuArchitecture: arm64
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-aarch64-live-iso.aarch64.iso
    version: 9.6.20250826-1
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-ppc64le-live-iso.ppc64le.iso
    version: 9.6.20250826-1
  - cpuArchitecture: s390x
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-s390x-live-iso.s390x.iso
    version: 9.6.20250826-1
  - cpuArchitecture: x86_64
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/4.21.0-ec.2/rhcos-4.21.0-ec.2-x86_64-live-iso.x86_64.iso
    version: 9.6.20251015-1
  - cpuArchitecture: arm64
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/pre-release/4.21.0-ec.2/rhcos-4.21.0-ec.2-aarch64-live-iso.aarch64.iso
    version: 9.6.20251015-1
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/pre-release/4.21.0-ec.2/rhcos-4.21.0-ec.2-ppc64le-live-iso.ppc64le.iso
    version: 9.6.20251015-1
  - cpuArchitecture: s390x
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/pre-release/4.21.0-ec.2/rhcos-4.21.0-ec.2-s390x-live-iso.s390x.iso
    version: 9.6.20251015-1
