apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  mustGatherImages:
  - name: cnv
    openshiftVersion: '4.8'
    url: registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5
  - name: ocs
    openshiftVersion: '4.8'
    url: registry.redhat.io/ocs4/ocs-must-gather-rhel8
  - name: lso
    openshiftVersion: '4.8'
    url: registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: '4.8'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso
    version: 48.84.202109241901-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.9'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.9/4.9.45/rhcos-4.9.45-x86_64-live.x86_64.iso
    version: 49.84.202207192205-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.10'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-x86_64-live.x86_64.iso
    version: 410.84.202210040010-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.10'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-aarch64-live.aarch64.iso
    version: 410.84.202210040011-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live.x86_64.iso
    version: 411.86.202210041459-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-aarch64-live.aarch64.iso
    version: 411.86.202210032347-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-s390x-live.s390x.iso
    version: 411.86.202210171842-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.11'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-ppc64le-live.ppc64le.iso
    version: 411.86.202210171844-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.12/4.12.0/rhcos-4.12.0-x86_64-live.x86_64.iso
    version: 412.86.202212081411-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.12/4.12.0/rhcos-4.12.0-aarch64-live.aarch64.iso
    version: 412.86.202212081411-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.12/4.12.0/rhcos-4.12.0-s390x-live.s390x.iso
    version: 412.86.202212081411-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.12'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.12/4.12.0/rhcos-4.12.0-ppc64le-live.ppc64le.iso
    version: 412.86.202212081411-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/latest-4.13/rhcos-4.13.0-ec.3-x86_64-live.x86_64.iso
    version: 413.86.202302162343-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/pre-release/latest-4.13/rhcos-4.13.0-ec.3-aarch64-live.aarch64.iso
    version: 413.86.202302162338-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/pre-release/latest-4.13/rhcos-4.13.0-ec.3-ppc64le-live.ppc64le.iso
    version: 413.86.202302162338-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.13'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/pre-release/latest-4.13/rhcos-4.13.0-ec.3-s390x-live.s390x.iso
    version: 413.86.202302162339-0
