apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  mustGatherImages:
  - name: cnv
    openshiftVersion: '4.8'
    url: registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5
  - name: ocs
    openshiftVersion: '4.8'
    url: registry.redhat.io/ocs4/ocs-must-gather-rhel8
  - name: lso
    openshiftVersion: '4.8'
    url: registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8
  osImages:
  - cpuArchitecture: x86_64
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.19/rhcos-4.19.19-x86_64-live-iso.x86_64.iso
    version: 9.6.20251023-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.19/4.19.19/rhcos-4.19.19-aarch64-live-iso.aarch64.iso
    version: 9.6.20251023-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.19/4.19.19/rhcos-4.19.19-ppc64le-live-iso.ppc64le.iso
    version: 9.6.20251023-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.19'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.19/4.19.19/rhcos-4.19.19-s390x-live-iso.s390x.iso
    version: 9.6.20251023-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.20/4.20.12/rhcos-4.20.12-x86_64-live-iso.x86_64.iso
    version: 9.6.20251023-0
  - cpuArchitecture: arm64
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.20/4.20.12/rhcos-4.20.12-aarch64-live-iso.aarch64.iso
    version: 9.6.20251023-0
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.20/4.20.12/rhcos-4.20.12-ppc64le-live-iso.ppc64le.iso
    version: 9.6.20251023-0
  - cpuArchitecture: s390x
    openshiftVersion: '4.20'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.20/4.20.12/rhcos-4.20.12-s390x-live-iso.s390x.iso
    version: 9.6.20251023-0
  - cpuArchitecture: x86_64
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.21/4.21.0/rhcos-4.21.0-x86_64-live-iso.x86_64.iso
    version: 9.6.20251212-1
  - cpuArchitecture: arm64
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.21/4.21.0/rhcos-4.21.0-aarch64-live-iso.aarch64.iso
    version: 9.6.20251212-1
  - cpuArchitecture: ppc64le
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.21/4.21.0/rhcos-4.21.0-ppc64le-live-iso.ppc64le.iso
    version: 9.6.20251212-1
  - cpuArchitecture: s390x
    openshiftVersion: '4.21'
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.21/4.21.0/rhcos-4.21.0-s390x-live-iso.s390x.iso
    version: 9.6.20251212-1
