apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  mustGatherImages:
  - name: cnv
    openshiftVersion: '4.8'
    url: registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5
  - name: ocs
    openshiftVersion: '4.8'
    url: registry.redhat.io/ocs4/ocs-must-gather-rhel8
  - name: lso
    openshiftVersion: '4.8'
    url: registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8
  osImages:
  - openshiftVersion: '4.8'
    rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso
    version: 48.84.202107202156-0
  - openshiftVersion: '4.9'
    rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.9.0-rc.0/rhcos-live-rootfs.x86_64.img
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.9.0-rc.0/rhcos-4.9.0-rc.0-x86_64-live.x86_64.iso
    version: 49.84.202109041651-0
  - openshiftVersion: '4.9'
    rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/arm64/dependencies/rhcos/pre-release/4.9.0-rc.4/rhcos-4.9.0-rc.4-aarch64-live-rootfs.aarch64.img
    url: https://mirror.openshift.com/pub/openshift-v4/arm64/dependencies/rhcos/pre-release/4.9.0-rc.4/rhcos-4.9.0-rc.4-aarch64-live.aarch64.iso
    version: 49.84.202109210947-0
