apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scality
  name: scality
  namespace: assisted-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scality
  template:
    metadata:
      labels:
        app: scality
    spec:
      containers:
        - image: scality/s3server
          imagePullPolicy: Always
          name: s3server
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_secret_access_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_access_key_id
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: aws_region
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: bucket
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: endpoint
            - name: S3DATAPATH
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: s3_data_path
            - name: S3METADATAPATH
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-s3
                  key: s3_metadata_path
          volumeMounts:
            - mountPath: /mnt/data
              name: scalityvol
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 2000Mi
      volumes:
        - name: scalityvol
          persistentVolumeClaim:
            claimName: scality-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scality
  # cloudserver-front supported as one of the default hostnames that can receive messages
  # to support other hostnamnes they need to be defined with HOST_NAME environment variable.
  name: cloudserver-front
  namespace: assisted-installer
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: scality
  clusterIP: None
status:
  loadBalancer: {}
